package cli

import (
	"github.com/cshaiku/goshi/internal/fs"
	"github.com/spf13/cobra"
)

func newFSApplyCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "apply <proposal-id>",
		Short: "Apply a previously generated fs write proposal",
		Long: `Apply a filesystem write proposal generated by 'goshi fs write'.

Applies the changes specified in the proposal. The proposal ID is provided
when you run 'goshi fs write'. Use '--dry-run' to preview changes without
applying them.

EXAMPLES:
  $ goshi fs apply abc123def456

  $ goshi fs apply abc123def456 --dry-run

EXIT CODES:
  0   - Success: Write proposal applied
  1   - Error: Invalid proposal ID or application failed`,
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			// Pass proposal ID directly.
			return fs.ApplyWriteProposal(args[0])
		},
	}
}
